# Generated by Django 3.2.1 on 2022-02-05 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnirAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=400, verbose_name='Ism Familiya')),
                ('age', models.FloatField(max_length=3, verbose_name='Yosh')),
                ('staj', models.CharField(max_length=20, verbose_name='Tajribangiz necha oy/yil ?')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telefon: ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Qoshimcha fikringiz: ')),
                ('turnir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.turnir')),
            ],
        ),
        migrations.RemoveField(
            model_name='turnirquestion',
            name='turnir',
        ),
        migrations.DeleteModel(
            name='Auth',
        ),
        migrations.DeleteModel(
            name='TurnirQuestion',
        ),
    ]
