# Generated by Django 3.2.1 on 2022-02-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220205_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnirauth',
            name='turnir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='main.turnir'),
        ),
        migrations.CreateModel(
            name='TurnirQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=400, verbose_name='Ism Familiya: ')),
                ('age', models.FloatField(max_length=3, verbose_name='Yosh')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telefon: ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Qoshimcha fikringiz: ')),
                ('turnir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.turnir')),
            ],
        ),
    ]
