# Generated by Django 3.2.1 on 2022-02-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220205_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telefon: ')),
                ('text', models.TextField(verbose_name='habar matni: ')),
            ],
        ),
    ]
