# Generated by Django 3.2.1 on 2022-02-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism: ')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon raqam: ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='XAbar Matni')),
            ],
        ),
    ]
