# Generated by Django 3.2.1 on 2022-02-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tadbir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tadbirning-Nomi')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Rasimi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('address', models.CharField(max_length=200, verbose_name='Manzil')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Qachon va nechida boshlanishi')),
            ],
            options={
                'verbose_name_plural': 'Tadbir',
            },
        ),
        migrations.CreateModel(
            name='TadbirsTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.TimeField(blank=True, null=True, verbose_name='Time Line')),
                ('text', models.CharField(max_length=200, verbose_name="Nima bo'lishi")),
                ('turnir', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tadbir_time', to='main.tadbir')),
            ],
            options={
                'verbose_name_plural': 'Tadbirs Time',
            },
        ),
    ]
