# Generated by Django 3.2.1 on 2022-02-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tadbir_tadbirstime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnirauth',
            name='turnir',
        ),
    ]
